config/routes.rb
Rails.application.routes.draw do
  resources :school_requests

  resources :feedbacks

  resources :learning_resources

  resources :completed_courses

  resources :degree_requirements

  resources :majors

  resources :enrollments  do
      get 'cal_hide'
    get 'cal_show'
    member do
    post 'toggle'
  end
  end

  resources :announcements

  resources :assignments
  resources :departments do
    resources :majors
  end
  resources :reviews

  get 'sections/all_sections'
  get 'sections/edit_all'
  get 'sections/all_sections2'
  get 'sections/search_sections'
  get 'sections/wishlist'
  get 'sections/dedupe'
  get 'sections/disperse'
  
  delete 'sections/destroy_multiple'

  resources :sections do
    resources :learning_resources
    resources :reviews
    resources :enrollments
    resources :assignments
    resources :announcements
    resources :users
    get 'students'
    collection { post :import }
  end
  

  resources :universities do
    get :autocomplete_course_name, on: :collection
    resources :departments
    resources :majors
  end

   as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions], :controllers => {:registrations => "registrations"}

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions] do
    members do
      patch :edit
    end
  end
  
  get 'static_pages/home'
  get 'static_pages/company'
  get 'static_pages/help'
  get 'static_pages/ambassador'
  get 'courses/all_courses'
  get 'courses/edit_all'
  
  delete 'courses/destroy_multiple'
  get 'static_pages/about'
  root 'static_pages#home'
  
  resource :devise
  resources :posts do
    resources :users 
  end
  resources :universities do
    resources :courses do
      get :autocomplete_section_teacher, on: :collection
      resources :posts
      post "course/new"
    end
  end
  resources :courses do
    get :autocomplete_section_teacher, on: :collection
    get 'alli'
    resources :sections do
      resources :enrollments do
        get 'cal_hide'
      end
    end
    resources :posts do
      resources :users
    end
  end
  
  
  resources :users do
    resources :enrollments do
      get 'cal_hide'
    end
    
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users = User.all
    @universities = University.all
   @autocomplete_items = Section.select(:section_name).distinct
      @autocomplete_subjects = Section.select(:subject).distinct
      @autocomplete_teachers = Section.select(:teacher).distinct
      @autocomplete_majors = Major.all
      @autocomplete_courses = Course.all
  end
  
  def ambassador
    
  end
  
  def company
    
  end
  def help
    
  end

  def about
     @universities = University.all
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="bs-docs-header">
  <div class="container">
    <div class="well">
<h1><center><%= image_tag "ShorelineLogoColor.png", width: 100 %><br><br>Mission</h1>

<p class="lead">Shoreline makes academic tools that encourage exploration and ownership over ones education. </p>
<p class="lead"><strong>Services</strong><br>
  <ul>
<h4><li>Course search</h4>
<h4><li>Wishlists</h4>
<h4><li>Data Ambassador Program</h4>
</ul>
</p>
<hr>
<p class="lead"><strong>What is a Data Ambassador?</strong><br>
Shoreline gets data with help from students like you! We call these helpers "Data Ambassadors", and they make information available on Shoreline better. Every school should have a great search tool for academic planning. Because not every school is digitized or has old computer systems, we provide a system for any school to integrate with, and let students be the IT staff!  
  </p>
<p class="lead"><strong>How can I become a Data Ambassador for my school?</strong><br>
Start by signing up for a Shoreline Ambassador account! You can choose to start data entry for your own school, or join existing Ambassadors. When you first become an Ambassador, you'll have to earn your keep. Earn points by helping curate data. You can make course data better by adding links to textbooks, learning materials, or becoming a Teacher Technology Assistant. </p>
<hr>

<h4>
  <center><p class="lead"><strong>What Students Think</strong></center>
  <i>"Using Shoreline feels like going to Hogwarts!"</i><br> - Anonymous<br><br>
  <i>"It's better than Yik Yak!"</i><br> - Anonymous<br><br>
<hr>
  </div>
    </div><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41312073-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/ambassador.html.erb
  <div class="container">
    <div class="well">
<center><h1>Bringing Shoreline to Your Campus</h1>
</center>
  <hr>
      <p class="lead"><center><%= link_to "Start a request for your school", new_school_request_path, class: 'btn btn-raised btn-primary' %></center></p>
      <hr>
<p class="lead">
  We will prioritize the process of data-scraping schools that have the most requests. However, you can also become a Data Ambassador and integrate the data yourself. This way, students can become their own IT personel. Integrating Shoreline with any school requires these three steps: 
  <ol><li><p class="lead">Become an <b class="text-primary">Ambassador</b>, by sending a <%= link_to "request form", new_feedback_path %></li>
    <li><p class="lead">Make a <b class="text-success">spreadsheet</b> of your school's course catalog</li>
    <li><p class="lead"><b class="text-danger">Upload</b> the spreadsheet to Shoreline</li>
</ol>
<p class="lead">That is all! Now your school has great online course catalog.

</p>
</div></div><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41312073-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/company.html.erb
<div class="container">
<div class="well">
<h1><center>
  <i class="fa fa-group"></i><br>
  Company
  </center></h1>
  <hr>
  <p class="lead"><h2>Team Member 1: <b><%= link_to "James Steininger", "http://jamessteininger.info", target: "_blank" %></b></h2><br><br>If you want to join the development team, email James Steininger (jesteininger@gmail.com) for more details. We are located in Saratoga, CA. </p>
  </div>
</div><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41312073-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/help.html.erb
<div class="container"><div class="well"><h1><center>Registration Help</center></h1>
  <hr>
  <div class="row">
    <div class="col-md-6">
         <%= image_tag "Search.png", class: "img-responsive" %>
    </div><div class="col-md-6">
         <h3>Use the search bar to quickly find classes by the GE code, the name of the course, the name of the teacher, or by the subject.</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
         <h3>Save everything to a wishlist so you can get them later.</h3>
    </div>
    <div class="col-md-6">
         <%= image_tag "Wishlist.png", class: "img-responsive" %>
    </div>
  </div><hr>
  <div class="row">
    <div class="col-md-6">
         <%= image_tag "Cal.png", class: "img-responsive" %>
    </div><div class="col-md-6">
         <h3>All your classes go on a calendar view, so you can see which classes have conflicting time slots. </h3>
    </div>
  </div><hr>
  <h2>Useful links:<br>
  <%= link_to "Chapman Add/Drop Form", "http://www.chapman.edu/students/academic-resources/registrar/_files/forms/registration.pdf", :target => "_blank" %>
    <br><br>Did you know you can create your own major?</h2><h4>Just fill out the <%= link_to "petition form", "http://www.chapman.edu/students/academic-resources/registrar/_files/forms/self-design-major-app.pdf", target: "_blank" %> and turn it into the registrar. 
  </h4>
</div>
</div><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41312073-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/home.html.erb
<body style="background-color: white;"><div class="intro"><div class="home-search"><div class="col-md-4 col-md-offset-4"><%= render 'layouts/messages' %>
  <center><br><br><br><h1 style="font-family: 'Open Sans'; font-size: 50px; font-weight: 100;"><%= image_tag "ShorelineLogoColor.png", width: 100 %><br>Shoreline</h1></center>
  

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41312073-4', 'auto');
  ga('send', 'pageview');

</script>

<script>
  $(function() {
   $('#test').addClass('animated fadeInUp');
});
</script>
  </center>
  
<div id="the-basics2">
  <%= form_tag(sections_wishlist_path, :method => "get", autofocus: true, id: "the-basics2  form-", class: 'for') do  %>
<div class="form-group col-md-">
  
  <%= text_field_tag :search, params[:search], id: "inputLarge ", class: "form-control typeahead", id: "auto_complete", :autofocus => true, placeholder: "Search for a Class, Teacher, Major, or Requirement" %>
    </div><center>
  <%= submit_tag "Search Shoreline", class: "btn btn-primary btn- btn-", :name => nil %>

<% end %>
</div>
  <center><h5 class="text-muted">Currently supporting Chapman University<br><%= link_to "Bring Shoreline to Your School", static_pages_ambassador_path %></h5></center>
  <%= javascript_tag "var autocomplete_items = #{ @autocomplete_items.pluck(:section_name).to_json };" %>
      <%= javascript_tag "var autocomplete_subjects = #{ @autocomplete_subjects.pluck(:subject).to_json };" %>
      <%= javascript_tag "var autocomplete_teachers = #{ @autocomplete_teachers.pluck(:teacher).to_json };" %>
  <%= javascript_tag "var autocomplete_ge = #{ @autocomplete_items.pluck(:ge).to_json };" %>
<script type="text/javascript">
$('#the-basics2 .typeahead').typeahead({ hint: true, highlight: true, minLength: 2 },
{ name: 'states', displayKey: 'value', source: substringMatcher(autocomplete_subjects), templates: {
  header: '<h3 style="padding-left: 10px;" class="league-name">Department</h3>'}
},{ name: 'states', displayKey: 'value', source: substringMatcher(autocomplete_ge), templates: {
  header: '<h3 style="padding-left: 10px;" class="league-name">GE</h3>'}
},
{name: 'nba-teams',displayKey: 'value',source: substringMatcher(autocomplete_items),templates: {header: '<h3 style="padding-left: 10px;" class="league-name">Name</h3>'}
},
{name: 'nba-teams',displayKey: 'value',source: substringMatcher(autocomplete_teachers),templates: {
header: '<h3 style="padding-left: 10px;" class="league-name">Teacher</h3>'}
}).on('typeahead:selected', function(e, data) {
$("#the-basics2 form").submit();
}).css();
</script>
<script>
  $('#hours').slider({ 
        formater: function(value) {
            return formatTime(minutesToTime(value));
        },
        
        tooltip_separator: " to ", 
    }).on("slideStop", drawTables);
  
  function drawTables() {
      
    }
  
</script>
  </div>
</div></div>