config/routes.rb
Rails.application.routes.draw do
  resources :school_requests

  resources :feedbacks

  resources :learning_resources

  resources :completed_courses

  resources :degree_requirements

  resources :majors

  resources :enrollments  do
      get 'cal_hide'
    get 'cal_show'
    member do
    post 'toggle'
  end
  end

  resources :announcements

  resources :assignments
  resources :departments do
    resources :majors
  end
  resources :reviews

  get 'sections/all_sections'
  get 'sections/edit_all'
  get 'sections/all_sections2'
  get 'sections/search_sections'
  get 'sections/wishlist'
  get 'sections/dedupe'
  get 'sections/disperse'
  
  delete 'sections/destroy_multiple'

  resources :sections do
    resources :learning_resources
    resources :reviews
    resources :enrollments
    resources :assignments
    resources :announcements
    resources :users
    get 'students'
    collection { post :import }
  end
  

  resources :universities do
    get :autocomplete_course_name, on: :collection
    resources :departments
    resources :majors
  end

   as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions], :controllers => {:registrations => "registrations"}

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions] do
    members do
      patch :edit
    end
  end
  
  get 'static_pages/home'
  get 'static_pages/company'
  get 'static_pages/help'
  get 'static_pages/ambassador'
  get 'courses/all_courses'
  get 'courses/edit_all'
  
  delete 'courses/destroy_multiple'
  get 'static_pages/about'
  root 'static_pages#home'
  
  resource :devise
  resources :posts do
    resources :users 
  end
  resources :universities do
    resources :courses do
      get :autocomplete_section_teacher, on: :collection
      resources :posts
      post "course/new"
    end
  end
  resources :courses do
    get :autocomplete_section_teacher, on: :collection
    get 'alli'
    resources :sections do
      resources :enrollments do
        get 'cal_hide'
      end
    end
    resources :posts do
      resources :users
    end
  end
  
  
  resources :users do
    resources :enrollments do
      get 'cal_hide'
    end
    
  end

end

app/models/major.rb
class Major < ActiveRecord::Base
  belongs_to :university
  belongs_to :department
  has_many :degree_requirements
  has_many :users
  has_and_belongs_to_many :courses
  accepts_nested_attributes_for :courses
  
  def total_credits
    counted_credits = 0
    degree_requirements.each do |f|
      counted_credits += 3
    end
    return counted_credits
  end
  
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: [:show, :edit, :update, :destroy]

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all.order('name ASC')
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
    @users = User.where(:major_id => @major.id)
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        format.html { redirect_to @major, notice: 'Major was successfully created.' }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1
  # PATCH/PUT /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to @major, notice: 'Major was successfully updated.' }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    @major.destroy
    respond_to do |format|
      format.html { redirect_to majors_url, notice: 'Major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def major_params
      params.require(:major).permit(:university_id, :credits, :name, :description, :department_id)
    end
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_form.html.erb
<%= form_for(@major) do |f| %>
  <% if @major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@major.errors.count, "error") %> prohibited this major from being saved:</h2>

      <ul>
      <% @major.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :university_id %><br>
    <%= f.collection_select :university_id, University.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.collection_select :department_id, Department.all, :id, :name %>
  </div>

Lower division credis

Upper division credits

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/majors/edit.html.erb
<h1>Editing major</h1>

<%= render 'form' %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

app/views/majors/index.html.erb
<h1>Majors</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>University</th>
      <th>Name</th>
      <th>Description</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @majors.each do |major| %>
      <tr>
        <td><%= link_to University.find(major.university_id).name, University.find(major.university_id) %></td>
        <td><%= link_to major.name, major %></td>
        <td><%= major.description %></td>
        <td><%= link_to major.department.name, major.department %></td>
        <td><%= link_to 'Show', major %></td>
        <td><%= link_to 'Edit', edit_major_path(major) %></td>
        <td><%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Major', new_major_path %>

app/views/majors/new.html.erb
<div class="container">
  <%= javascript_include_tag :defaults, "nested_form" %>
  
<h1>New major</h1>

<%= render 'form' %>

<%= link_to 'Back', majors_path %>
  
</div>

app/views/majors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @major.name %>
</h1>
Of <%= link_to @major.university.name, @major.university %> within the <%= link_to "Department of " + @major.department.name, @major.department %><br>
<%= link_to 'Edit', edit_major_path(@major) %> | <%= link_to 'Back', majors_path %>
<hr>

<div class="row">
  <div class="col-md-3">
    <div class="well">
    <h4>Enrolled Students (<%= @users.count %>)</h4>
    <% @users.each do |f| %>
    <p><%= link_to f.full_name, f %></p>
    <% end %>
  </div>
  </div>
  <div class="col-md-9">
    <div class="well">



<h3><%= link_to "Requirements", degree_requirements_path %> (<%= @major.total_credits %> credits ) </h3>

<% @major.degree_requirements.each do |f| %>

<p>
  <% if f.course.presence %><%= link_to f.course.full_name, f.course %> - <%= f.course.credits %> Credits <% if user_signed_in? %><% current_user.enrollments.each do |g| %> 
          <% if g.section.course.id == f.course.id %>
            <span class="label label-success">Currently Enrolled</span>
  <% end %><% end %><% end %><% end %>
</p>
<% end %>