config/routes.rb
Rails.application.routes.draw do
  resources :school_requests

  resources :feedbacks

  resources :learning_resources

  resources :completed_courses

  resources :degree_requirements

  resources :majors

  resources :enrollments  do
      get 'cal_hide'
    get 'cal_show'
    member do
    post 'toggle'
  end
  end

  resources :announcements

  resources :assignments
  resources :departments do
    resources :majors
  end
  resources :reviews

  get 'sections/all_sections'
  get 'sections/edit_all'
  get 'sections/all_sections2'
  get 'sections/search_sections'
  get 'sections/wishlist'
  get 'sections/dedupe'
  get 'sections/disperse'
  
  delete 'sections/destroy_multiple'

  resources :sections do
    resources :learning_resources
    resources :reviews
    resources :enrollments
    resources :assignments
    resources :announcements
    resources :users
    get 'students'
    collection { post :import }
  end
  

  resources :universities do
    get :autocomplete_course_name, on: :collection
    resources :departments
    resources :majors
  end

   as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions], :controllers => {:registrations => "registrations"}

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions] do
    members do
      patch :edit
    end
  end
  
  get 'static_pages/home'
  get 'static_pages/company'
  get 'static_pages/help'
  get 'static_pages/ambassador'
  get 'courses/all_courses'
  get 'courses/edit_all'
  
  delete 'courses/destroy_multiple'
  get 'static_pages/about'
  root 'static_pages#home'
  
  resource :devise
  resources :posts do
    resources :users 
  end
  resources :universities do
    resources :courses do
      get :autocomplete_section_teacher, on: :collection
      resources :posts
      post "course/new"
    end
  end
  resources :courses do
    get :autocomplete_section_teacher, on: :collection
    get 'alli'
    resources :sections do
      resources :enrollments do
        get 'cal_hide'
      end
    end
    resources :posts do
      resources :users
    end
  end
  
  
  resources :users do
    resources :enrollments do
      get 'cal_hide'
    end
    
  end

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  validates :user_id, presence: true 
  validates :section_id, presence: true
  
  belongs_to :user
  belongs_to :section
  
  def cal_hide
    this.update_attribute(:cal_hidden, true)
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:edit, :update, :destroy]
   respond_to :html, :xml, :json
  def toggle
    @enrollment = Enrollment.find(params[:id])
    @user = @enrollment.user

    if @enrollment.update_attributes(:cal_hidden => params[:cal_hidden])
      redirect_to @user
    else
      redirect_to @user
    end
  end
  
  def cal_hide
    @enrollment = Enrollment.find(params[:enrollment_id])
    @enrollment.update_attribute(:cal_hidden, true)
    @user = @enrollment.user
    redirect_to @user
  end
  
  def cal_show
    @enrollment = Enrollment.find(params[:enrollment_id])
    @enrollment.update_attribute(:cal_hidden, false)
    @user = @enrollment.user
    redirect_to @user
    
  end
  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
   # @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  
  # POST /enrollments
  # POST /enrollments.json
  def create
    @user = User.find(params[:user_id])
    @enrollment = @user.enrollments.new(enrollment_params)
    @section = @enrollment.section

    respond_to do |format|
      if @enrollment.save
        format.js
        format.html { redirect_to sections_wishlist_path, notice: 'Added to wishlist.' }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      else
        format.js
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to sections_wishlist_path }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @section = @enrollment.section
    @enrollment.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to sections_wishlist_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:cal_hidden, :user_id, :section_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :section_id %><br>
    <%= f.number_field :section_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrollments/cal_show.js.erb
alert('djakd');
$("#wishlist").html("<%= escape_javascript(render(:partial => 'users/wishlist')) %>")

app/views/enrollments/create.js.erb
$("#<%= @section.id =%>enroll_form").html("<%= escape_javascript(render(:partial => 'sections/unenroll', locals: {section: @section})) %> ")
$("#followers").html('<%= Section.all.count %>')
$("#wishlist").html("<%= escape_javascript(render(:partial => 'sections/wishlist')) %>")

app/views/enrollments/destroy.js.erb
$("#<%= @section.id =%>enroll_form").html("<%= escape_javascript(render(:partial => 'sections/enroll', locals: {section: @section})) %> ")
$("#wishlist").html("<%= escape_javascript(render(:partial => 'sections/wishlist')) %>")

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.user.full_name %> </td>
        <td><%= enrollment.section.name %> with Professor <%= enrollment.section.teacher %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @enrollment.user_id %>
</p>

<p>
  <strong>Section:</strong>
  <%= @enrollment.section_id %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>